### ISSUE TITLE
Policy values aren't encoded

### ISSUE THREAD

**Issue by reinkrul** [nuts-foundation/uzi-did-x509-issuer#11]
Meaning it'll produce an invalid DID when including a field that contains a character not supported by the DID spec. Or, if it contains a double colon (it'll make the did:x509 string invalid);

```
method-specific-id = *( *idchar ":" ) 1*idchar
idchar             = ALPHA / DIGIT / "." / "-" / "_" / pct-encoded
pct-encoded        = "%" HEXDIG HEXDIG
```

**Comment by stevenvegt** [comment]
The did library does not support URL encoded values, also see this issue: build-trust/did#17. This probably needs some serious overhaul.

**Comment by reinkrul** [comment]
> The did library does not support URL encoded values, also see this issue: [build-trust/did#17](https://github.com/build-trust/did/issues/17). This probably needs some serious overhaul.

Do you want to fix this, or is it only an observation?
